### ISSUE TITLE
Support for Rails 7

### ISSUE THREAD

**Issue by chrisblatchley** [macfanatic/active_admin-state_machine#15]
Current Gemfile version is locked to rails `~> 6.0`

**Comment by chrisblatchley** [comment]
i will be working on this myself in the meantime but not sure on the timeline.

**Comment by macfanatic** [comment]
I don't actively maintain the library anymore, but if you find using it with rails 7 doesn't require many changes let me know and I can see about releasing a new version with the restriction removed.
